version: '3.1'

services:
  mysql-db:
    image: mysql:5.7
    user: '1000:50'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - ./data/mysql-db/:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql-db
    depends_on:
      - mysql-db
    links:
      - mysql-db
  php-app:
    build:
      context: ./config
      dockerfile: php.dockerfile
    container_name: app
    restart: always
    working_dir: /var/www
    volumes: 
      - ./src:/var/www
    depends_on:
      - mysql-db
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx-app
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./config/nginx:/etc/nginx/conf.d
